"""Compliance report generator — MAS (Singapore) and MiCA (EU) templates."""

import csv
import io
import json
from datetime import datetime, timezone
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.database import Agent, AuditEvent

# PDF support — optional dependency
try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    HAS_REPORTLAB = True
except ImportError:
    HAS_REPORTLAB = False


async def generate_compliance_report(
    db: AsyncSession,
    org_id: UUID,
    jurisdiction: str,
    agent_did: str | None,
    date_from: datetime,
    date_to: datetime,
    fmt: str = "json",
) -> dict | str:
    """Generate a compliance report for the given jurisdiction and date range."""

    # Fetch agents
    agent_query = select(Agent).where(Agent.organization_id == org_id)
    if agent_did:
        agent_query = agent_query.where(Agent.did == agent_did)
    result = await db.execute(agent_query)
    agents = result.scalars().all()

    agent_ids = [a.agent_id for a in agents]

    # Fetch audit events in date range
    event_query = (
        select(AuditEvent)
        .where(
            AuditEvent.organization_id == org_id,
            AuditEvent.agent_id.in_(agent_ids),
            AuditEvent.timestamp >= date_from,
            AuditEvent.timestamp <= date_to,
        )
        .order_by(AuditEvent.timestamp.asc())
    )
    result = await db.execute(event_query)
    events = result.scalars().all()

    # Build report structure
    if jurisdiction == "MAS":
        report = _build_mas_report(agents, events, date_from, date_to)
    elif jurisdiction == "MiCA":
        report = _build_mica_report(agents, events, date_from, date_to)
    else:
        report = _build_generic_report(agents, events, date_from, date_to)

    if fmt == "csv":
        return _report_to_csv(report)

    if fmt == "pdf":
        if not HAS_REPORTLAB:
            raise RuntimeError("PDF export requires reportlab: pip install reportlab")
        return _report_to_pdf(report)

    return report


def _build_mas_report(agents, events, date_from, date_to) -> dict:
    """MAS FAA-N16 compliant report structure."""
    total_actions = len(events)
    violations = [e for e in events if e.outcome == "violation"]
    total_spend = sum(float(e.value_usd or 0) for e in events if e.outcome == "success")

    return {
        "report_type": "MAS_FAA_N16",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "report_period": {
            "from": date_from.isoformat() + "Z",
            "to": date_to.isoformat() + "Z",
        },
        "regulatory_framework": "Monetary Authority of Singapore — Financial Advisers Act Notice FAA-N16",
        "disclaimer": (
            "This report is generated by Bouclier Protocol for informational purposes. "
            "It does not constitute legal or compliance advice. Organizations should consult "
            "licensed legal professionals for regulatory compliance verification."
        ),
        "summary": {
            "total_agents": len(agents),
            "total_actions": total_actions,
            "total_violations": len(violations),
            "violation_rate": f"{(len(violations) / total_actions * 100):.2f}%" if total_actions else "0%",
            "total_spend_usd": f"{total_spend:.2f}",
        },
        "agents": [
            {
                "agent_id": a.agent_id,
                "did": a.did,
                "agent_address": a.agent_address,
                "model": a.model,
                "status": a.status,
                "registered_at": a.created_at.isoformat() + "Z",
            }
            for a in agents
        ],
        "action_log": [
            {
                "timestamp": e.timestamp.isoformat() + "Z",
                "agent_id": e.agent_id,
                "tx_hash": e.tx_hash,
                "target_contract": e.target_contract,
                "function_selector": e.function_selector,
                "value_usd": e.value_usd,
                "outcome": e.outcome,
                "violation_type": e.violation_type,
            }
            for e in events
        ],
        "violations": [
            {
                "timestamp": e.timestamp.isoformat() + "Z",
                "agent_id": e.agent_id,
                "violation_type": e.violation_type,
                "value_usd": e.value_usd,
                "target_contract": e.target_contract,
                "tx_hash": e.tx_hash,
            }
            for e in violations
        ],
        "integrity": {
            "data_source": "Bouclier Protocol on-chain audit trail (Base L2)",
            "immutability": "Events recorded on EVM blockchain — tamper-proof",
            "ipfs_anchoring": "Audit records optionally anchored to IPFS for redundancy",
        },
    }


def _build_mica_report(agents, events, date_from, date_to) -> dict:
    """MiCA Article 38 compliant report — EU crypto-asset services."""
    total_actions = len(events)
    violations = [e for e in events if e.outcome == "violation"]
    total_spend = sum(float(e.value_usd or 0) for e in events if e.outcome == "success")

    # Group spend by token (if we had token data — simplified here)
    return {
        "report_type": "MiCA_Article_38",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "report_period": {
            "from": date_from.isoformat() + "Z",
            "to": date_to.isoformat() + "Z",
        },
        "regulatory_framework": "EU Markets in Crypto-Assets Regulation — Article 38",
        "disclaimer": (
            "This report is generated by Bouclier Protocol for informational purposes. "
            "It does not constitute legal or compliance advice. Organizations should consult "
            "EU-licensed legal professionals for MiCA compliance verification."
        ),
        "summary": {
            "total_agents": len(agents),
            "total_actions": total_actions,
            "total_violations": len(violations),
            "total_spend_usd": f"{total_spend:.2f}",
            "compliance_violations_detected": len(violations) > 0,
        },
        "agent_identities": [
            {
                "did": a.did,
                "agent_address": a.agent_address,
                "registration_timestamp": a.created_at.isoformat() + "Z",
                "model": a.model,
                "current_status": a.status,
            }
            for a in agents
        ],
        "permission_changes": [],  # Would be populated from PermissionVault events
        "transaction_log": [
            {
                "timestamp": e.timestamp.isoformat() + "Z",
                "agent_id": e.agent_id,
                "tx_hash": e.tx_hash,
                "target": e.target_contract,
                "value_usd": e.value_usd,
                "outcome": e.outcome,
                "violation_type": e.violation_type,
            }
            for e in events
        ],
        "compliance_violations": [
            {
                "timestamp": e.timestamp.isoformat() + "Z",
                "agent_id": e.agent_id,
                "type": e.violation_type,
                "severity": "high" if e.violation_type in ("DAILY_CAP_EXCEEDED", "AGENT_REVOKED") else "medium",
                "details": f"Transaction to {e.target_contract} blocked: {e.violation_type}",
            }
            for e in violations
        ],
        "cryptographic_integrity": {
            "blockchain": "Base L2 (Ethereum rollup)",
            "data_immutability": "All events are on-chain and verifiable",
            "ipfs_cid_chain": "Audit records optionally pinned to IPFS",
        },
    }


def _build_generic_report(agents, events, date_from, date_to) -> dict:
    """Generic compliance report."""
    total_actions = len(events)
    violations = [e for e in events if e.outcome == "violation"]
    total_spend = sum(float(e.value_usd or 0) for e in events if e.outcome == "success")

    return {
        "report_type": "generic",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "report_period": {"from": date_from.isoformat(), "to": date_to.isoformat()},
        "summary": {
            "agents": len(agents),
            "actions": total_actions,
            "violations": len(violations),
            "spend_usd": f"{total_spend:.2f}",
        },
        "agents": [{"did": a.did, "status": a.status, "model": a.model} for a in agents],
        "events": [
            {
                "timestamp": e.timestamp.isoformat(),
                "agent_id": e.agent_id,
                "outcome": e.outcome,
                "value_usd": e.value_usd,
            }
            for e in events
        ],
    }


def _report_to_csv(report: dict) -> str:
    """Convert the action/event log from a report to CSV format."""
    output = io.StringIO()
    events = report.get("action_log") or report.get("transaction_log") or report.get("events", [])

    if not events:
        return "No events in report period\n"

    writer = csv.DictWriter(output, fieldnames=events[0].keys())
    writer.writeheader()
    writer.writerows(events)
    return output.getvalue()


def _report_to_pdf(report: dict) -> bytes:
    """Render report as a styled PDF document. Returns raw PDF bytes."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=20 * mm, bottomMargin=15 * mm)
    styles = getSampleStyleSheet()
    story = []

    title_style = ParagraphStyle("Title", parent=styles["Title"], fontSize=16, textColor=colors.HexColor("#111111"))
    heading_style = ParagraphStyle("Heading", parent=styles["Heading2"], fontSize=12, spaceAfter=6)
    body_style = styles["BodyText"]

    # Title
    report_type = report.get("report_type", "Compliance Report")
    story.append(Paragraph(f"Bouclier — {report_type} Report", title_style))
    story.append(Spacer(1, 8 * mm))

    # Summary
    summary = report.get("summary", {})
    if summary:
        story.append(Paragraph("Summary", heading_style))
        for k, v in summary.items():
            story.append(Paragraph(f"<b>{k.replace('_', ' ').title()}</b>: {v}", body_style))
        story.append(Spacer(1, 5 * mm))

    # Period
    period = report.get("report_period", {})
    if period:
        story.append(Paragraph(f"Period: {period.get('from', '')} — {period.get('to', '')}", body_style))
        story.append(Spacer(1, 5 * mm))

    # Events table
    events = report.get("action_log") or report.get("transaction_log") or report.get("events", [])
    if events:
        story.append(Paragraph("Event Log", heading_style))
        cols = list(events[0].keys())[:6]
        header = [c.replace("_", " ").title() for c in cols]
        data = [header]
        for ev in events[:200]:
            data.append([str(ev.get(c, ""))[:30] for c in cols])

        table = Table(data, repeatRows=1)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#FF451A")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 7),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F4F4F5")]),
        ]))
        story.append(table)
        story.append(Spacer(1, 5 * mm))

    # Violations summary
    violations = report.get("violations") or report.get("compliance_violations", [])
    if violations:
        story.append(Paragraph(f"Violations ({len(violations)})", heading_style))
        for v in violations[:50]:
            story.append(Paragraph(
                f"• {v.get('timestamp', '')} — {v.get('violation_type') or v.get('type', '')} "
                f"(Agent: {v.get('agent_id', 'N/A')})",
                body_style,
            ))

    # Footer
    story.append(Spacer(1, 10 * mm))
    story.append(Paragraph(
        f"Generated by Bouclier Protocol at {report.get('generated_at', '')}",
        ParagraphStyle("Footer", parent=body_style, fontSize=7, textColor=colors.grey),
    ))

    doc.build(story)
    return buf.getvalue()
